### ISSUE TITLE
RuntimeError: Unable to open ../shape_predictor_68_face_landmarks.dat

### ISSUE THREAD

**Issue by dtdsouza199** [MarekKowalski/FaceSwap#18]
hi there i am getting the above error while trying to use the program. any help on this would be great

**Comment by MarekKowalski** [comment]
Hi,

As mentioned in zad2.py, the file can be downloaded from:
http://sourceforge.net/projects/dclib/files/dlib/v18.10/shape_predictor_68_face_landmarks.dat.bz2

Marek
